import Head from "next/head";
import Poster from "@/components/Poster";
import TopEvents from "@/components/TopEvents";
import MainInfo from "@/components/MainInfo";
import HowToUse from "@/components/HowToUse";
import Subscription from "@/components/Subscription";
import { getTopEvents } from "@/utils/api";

export const getServerSideProps = async () => {
  const res = await getTopEvents();

  return {
    props: {
      topEventsList: res,
    },
  };
};

export default function Home({
  isLoggedIn,
  isEmailSelected,
  onEmailSelection,
  onCodeSend,
  isSubscribed,
  isInfoToolTipOpen,
  onInfoToolTipClose,
  topEventsList,
}) {
  return (
    <>
      <Head>
        <title>МосСобытия</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={``}>
        <Poster />
        <TopEvents topEventsList={topEventsList} />
        <MainInfo />
        <HowToUse />
        <Subscription
          isLoggedIn={isLoggedIn}
          isEmailSelected={isEmailSelected}
          onEmailSelection={onEmailSelection}
          onCodeSend={onCodeSend}
          isSubscribed={isSubscribed}
          isInfoToolTipOpen={isInfoToolTipOpen}
          onInfoToolTipClose={onInfoToolTipClose}
        />
      </main>
    </>
  );
}
